# --- general --- #

ext: ''
conda_prefix:   ''


# --- vibrant --- #

vibrant_db: ''


# --- virsorter2 --- #

virsorter2_db: ''


# --- genomad --- #

genomad_db: ''


# --- checkv --- #

checkv_db: ''
