#'''Slurm job submission resource config.'''#


__default__:
    nCPU: 1
    mem: 8000
    output: "logs/{rule}/{wildcards}.out" # Wildcards are the most unconstrained therefore least findable
    # error: "logs/{rule}.{wildcards}.%j.err" # To redirect all STDOUT to the same file. Also removed in run_msw.sh
    job-name: "{rule}.{wildcards}.%j"


sample_rule:
    mem : 100000
    nCPU: 10


first_rule:
    mem : 20000
    nCPU: 5


python_rule:
    mem : 80000
    nCPU: 20

