#'''Parameters config.'''#


# --- general --- #

some_constant:   2500


# assembly option
option: 'meta'



# --- first_rule --- #
#host_reference_database: '/storage/tools/camp_short-read-quality-control/Databases/GRCh38_28122022/GCA_000001405.15_GRCh38_genomic'
vibrant_database: '/storage/tools/anaconda3/envs/vibrant_env/VIBRANT/databases/'
other_constant:    10000
