#'''Computational resource config.'''#


installation_threads: 4


# # --- general --- #

assembly_threads: 30
assembly_mem_mb:  200000


# --- vibrant --- #

vibrant_threads: 20


# --- virsorter --- #

virsorter_threads: 20
min_ctg_len: 1500


# --- checkv --- #

checkv_threads: 30

