#'''Computational resource config.'''#

# assembly

count_reads_mem_mb: 100000
# # --- general --- #
#
assembly_threads: 30
assembly_mem_mb:  200000



# --- sample_rule --- #

sample_rule_threads: 10
sample_rule_mem_mb: 100000


# --- vibrant --- #

vibrant_rule_threads: 10
first_rule_mem_mb: 20000


# --- virsorter --- #
virsorter_rule_threads: 10
virsorter_min_contig_length: 1500

# --- checkv --- #
checkv_rule_threads: 20

